services:
  # A Docker web service
  - type: web
    plan: free
    name: PiroAutoFilterBot
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github/ritheshrkrm/PiroAutoFilterBot.git # optional
    region: oregon # optional (defaults to oregon)
    branch: master # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL 
        sync: false 
      - key: CHANNELS 
        sync: false
      - key: ADMINS
        sync: false    
      - key: LOG_CHANNEL
        sync: false
    healthCheckPath: /

#End of yaml
